"""Stable application Interfaces for authoritative domain aggregates."""

from __future__ import annotations

from typing import Mapping, Protocol, runtime_checkable


@runtime_checkable
class ProjectModule(Protocol):
    def v2_ready(self) -> bool: ...

    def create_project(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def provision_default_project(self, *, user_id: str, username: str) -> dict[str, object]: ...

    def update_project(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def archive_project(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def unarchive_project(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def project(self, project_id: str, user: dict[str, object]) -> dict[str, object]: ...

    def list_projects(self, user: dict[str, object]) -> list[dict[str, object]]: ...

    def add_member(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def remove_member(self, *args: object, **kwargs: object) -> None: ...

    def list_project_members(
        self, project_id: str, user: dict[str, object]
    ) -> list[dict[str, object]]: ...

    def transfer_project_owner(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def attach_workspace(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def set_primary_workspace(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def replace_primary_workspace(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def detach_workspace(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def list_task_relationships(
        self, project_id: str, user: dict[str, object]
    ) -> list[dict[str, object]]: ...

    def create_task_relationship(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def delete_task_relationship(self, *args: object, **kwargs: object) -> None: ...

    def project_console_summaries(self, user: dict[str, object]) -> list[dict[str, object]]: ...

    def project_console_summary(
        self, project_id: str, user: dict[str, object]
    ) -> dict[str, object]: ...


@runtime_checkable
class WorkspaceModule(Protocol):
    def v2_ready(self) -> bool: ...

    def create_workspace(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def create_workspace_and_attach(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def attach_workspace(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def workspace_create_replay(
        self, *args: object, **kwargs: object
    ) -> dict[str, object] | None: ...

    def update_workspace(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def unregister_workspace(self, *args: object, **kwargs: object) -> None: ...

    def workspace(self, workspace_id: str, user: dict[str, object]) -> dict[str, object]: ...

    def list_workspaces(
        self, user: dict[str, object], *, project_id: str | None = None
    ) -> list[dict[str, object]]: ...

    def workspace_console_entries(
        self, user: dict[str, object], *, include_unregistered: bool = False
    ) -> list[dict[str, object]]: ...

    def workspace_console_entry(
        self, workspace_id: str, user: dict[str, object]
    ) -> dict[str, object]: ...

    def environment(
        self,
        environment_id: str,
        user: dict[str, object],
        *,
        include_disabled: bool = False,
    ) -> dict[str, object]: ...


@runtime_checkable
class EnvironmentReader(Protocol):
    def v2_ready(self) -> bool: ...

    def environment(
        self,
        environment_id: str,
        user: dict[str, object],
        *,
        include_disabled: bool = False,
    ) -> dict[str, object]: ...


@runtime_checkable
class WorkspaceReader(Protocol):
    def v2_ready(self) -> bool: ...

    def workspace(self, workspace_id: str, user: dict[str, object]) -> dict[str, object]: ...


@runtime_checkable
class EnvironmentModule(EnvironmentReader, Protocol):
    def create_environment(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def update_environment(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def disable_environment(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def list_environments(
        self, user: dict[str, object], *, include_disabled: bool = False
    ) -> list[dict[str, object]]: ...


class ContextModule(Protocol):
    def v2_ready(self) -> bool: ...

    def save_draft(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def get_context(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def publish(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def list_versions(self, *args: object, **kwargs: object) -> list[dict[str, object]]: ...

    def get_version(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def diff_versions(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def create_candidate(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def list_candidates(self, *args: object, **kwargs: object) -> list[dict[str, object]]: ...

    def accept_candidate(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def reject_candidate(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def create_fragment(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def list_fragments(self, *args: object, **kwargs: object) -> list[dict[str, object]]: ...

    def preview_task_context_update(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def confirm_task_context_update(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def task_context(self, *args: object, **kwargs: object) -> dict[str, object]: ...


class TaskLifecycleModule(Protocol):
    """Compatibility marker retained only for type migration; no runtime export."""

    def v2_ready(self) -> bool: ...


class ConversationModule(Protocol):
    """Canonical Task/Turn/Item application Interface."""

    def v2_ready(self) -> bool: ...

    def create_task(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def create_turn(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def retry_turn(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def request_steer(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def request_interrupt(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def resolve_approval(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def preview_fork(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def confirm_fork(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def cancel_task(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def archive_task(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def unarchive_task(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def update_task_title(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def read_task(self, *args: object, **kwargs: object) -> dict[str, object]: ...

    def list_turns(self, *args: object, **kwargs: object) -> list[dict[str, object]]: ...

    def list_items(self, *args: object, **kwargs: object) -> list[dict[str, object]]: ...


Actor = Mapping[str, object]
